CREATE TABLE ROLE (
	id INTEGER PRIMARY KEY NOT NULL,
	name TEXT NOT NULL
);

CREATE TABLE SOCIAL_INITIATIVE (
	id INTEGER PRIMARY KEY NOT NULL,
	name TEXT NOT NULL
);

CREATE TABLE USER (
	id INTEGER PRIMARY KEY NOT NULL,
	role_id INTEGER,
	socialinit_id INTEGER,
	FOREIGN KEY (role_id) REFERENCES ROLE(id),
	FOREIGN KEY (socialinit_id) REFERENCES SOCIAL_INITIATIVE(id),
	username TEXT NOT NULL,
	age INTEGER NOT NULL,
	pw VARCHAR(64),
	first_name VARCHAR(32),
	last_name VARCHAR(32)
);

CREATE TABLE IMPACT_LEARNER (
	id INTEGER PRIMARY KEY NOT NULL,
	FOREIGN KEY (id) REFERENCES USER(id)
);

CREATE TABLE IMPACT_CONSULTANT (
	id INTEGER PRIMARY KEY NOT NULL,
	FOREIGN KEY (id) REFERENCES USER(id)
);
