CREATE TABLE ROLES (
	id INTEGER PRIMARY KEY NOT NULL, 
	name TEXT NOT NULL
);

CREATE TABLE SOCIAL_INIT (
	id INTEGER PRIMARY KEY NOT NULL, 
	name TEXT NOT NULL
);

CREATE TABLE USERS (
	id INTEGER PRIMARY KEY NOT NULL, 
	role_id INTEGER,
	socialinit_id INTEGER, 
	FOREIGN KEY (role_id) REFERENCES ROLES(id), 
	FOREIGN KEY (socialinit_id) REFERENCES SOCIAL_INIT(id), 
	username TEXT NOT NULL, 
	age INTEGER NOT NULL, 
	pw VARCHAR(64),
	first_name VARCHAR(32),
	last_name VARCHAR(32)
);

CREATE TABLE IMPACT_LEARNERS (
	id INTEGER PRIMARY KEY NOT NULL,
	FOREIGN KEY (id) REFERENCES USERS(id)
);

CREATE TABLE IMPACT_CONSULTANTS (
	id INTEGER PRIMARY KEY NOT NULL, 
	FOREIGN KEY (id) REFERENCES USERS(id)
);
